name: alchemist
description: A support package that aims to make golden testing in Flutter
  easier and more streamlined.
version: 0.3.1
homepage: https://github.com/Betterment/alchemist
repository: https://github.com/Betterment/alchemist

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  test: ^1.17.12
  very_good_analysis: 2.4.0

flutter:
  uses-material-design: true
  # Used for readable platform golden tests.
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
