name: Bug Report
description: Create a report to help us improve.
title: "fix: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues.
          required: true

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Version
      description: |
        What version are you running?
      placeholder: "1.2.0"

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description: |
        Give us a clear and concise description of what the bug is and what happened.
      placeholder: It throws an error if I ...

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Steps to reproduce
      description: |
        What steps can we take to reproduce the bug?
      placeholder: |
        1. When golden tests are setup with ...
        2. It does [this] instead of [that] ...
        3. I think it should do [that] because of [this].

  - type: textarea
    id: expected
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: |
        What did you expect to happen?
      placeholder: |
        When running ..., it should ...

  - type: textarea
    id: screenshots
    validations:
      required: false
    attributes:
      label: Screenshots
      description: |
        If you have any screenshots, please attach them here.

  - type: textarea
    id: comments
    attributes:
      label: Additional context and comments
      description: |
        Anything else you want to say?
